In [4]:
import numpy as np

In [5]:
np.amin([10,3,2,7,10,1])

1

In [6]:
np.amax([10,3,2,7,10,1])

10

In [7]:
np.mean([10,3,2,7,10,1])

5.5

In [8]:
np.median([10,3,2,7,10,1])

5.0

In [10]:
np.std([10,3,2,7,10,1])

3.685557397915997

In [11]:
np.var([10,3,2,7,10,1])

13.583333333333334

In [12]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.sort([10,3,2,7,10,1])

array([ 1,  2,  3,  7, 10, 10])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [18]:
np.zeros(5)+5

array([5., 5., 5., 5., 5.])

In [21]:
d=np.arange(0,9,1)
d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.random.rand(1)

array([0.35870508])

In [23]:
np.random.randn(25)

array([ 2.58788276,  0.33529962, -2.05102035,  1.22373834,  1.8107988 ,
       -0.7261058 , -1.36632689,  0.76078014, -0.95733761,  0.71622274,
        2.47779149,  1.87803394,  0.76540436, -0.91899013, -1.86469318,
        0.13684271,  1.42520948,  0.52011961,  0.07076034,  0.27106642,
        0.93756615, -0.84151843,  2.15169845,  0.36723834,  0.58045518])

In [25]:
np.random.rand(25).reshape(5,5)

array([[0.13123414, 0.28463679, 0.94503403, 0.09429907, 0.37475174],
       [0.45030726, 0.76638635, 0.77756287, 0.02776795, 0.79977094],
       [0.95433073, 0.65736152, 0.59287312, 0.70699094, 0.50076582],
       [0.89401337, 0.08596124, 0.98310344, 0.65585381, 0.17737879],
       [0.65068879, 0.50639097, 0.71307475, 0.70614808, 0.07970007]])

In [30]:
z=np.linspace(0,100,20)

In [31]:
z

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [32]:
sd=np.arange(1,26).reshape(5,5)

In [33]:
sd

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
sd[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
sd[0:,3]

array([ 4,  9, 14, 19, 24])

In [37]:
sd

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
sd[1,3]

9

In [39]:
len(sd)

5

In [40]:
sd[::2,:]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [41]:
sd[:,[1,4]]

array([[ 2,  5],
       [ 7, 10],
       [12, 15],
       [17, 20],
       [22, 25]])

In [42]:
sd

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
sd[sd>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25])

In [46]:
b_arr=sd>4

In [47]:
sd[b_arr]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [50]:
crid_data=np.loadtxt("cric_data.tsv",skiprows=1)
crid_data


array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 14.,  99., 110., 362.]])

In [52]:
sachin=crid_data[:,1]
dravid=crid_data[:,2]

In [53]:
sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [54]:
dravid

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])